server:
  port: 3344
env: prod
spring:
  application:
    name: cloud-config-center
  cloud:
    gateway:
      config:
        server:
          
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: config-center3344
    prefer-ip-address: true